// min and max included
function randomIntFromInterval(min: number, max: number) {
    return Math.floor(Math.random() * (max - min + 1) + min)
}

function randomValue(): number {
    return randomIntFromInterval(1, 10)
}

interface TraitType { trait_type: string, value: number }

export function randomAttributes(): TraitType[] {
    const attributes = [
        'Perseverance',
        'Peacefulness',
        'Grit',
        'Temperance',
        'Brazenness',
        'Egocentrism',
        'Emotional',
        'Acuity',
        'Perception',
        'Charm',
        'Courage',
        'Empathy',
        'Aggression',
        'Imagination',
        'Patience',
        'Cruelty',
        'Meekness',
        'Vivacity',
        'Coordination',
        'Generosity',
        'Narcissism',
        'Lugubriousness',
        'Adventurousness',
        'Poise',
        'Paternalism',
        'Delicacy',
        'Cleanliness',
        'Health',
        'Self-Esteem',
        'Wonderment',
        'Deceptiveness',
        'Willingness',
        'Knowledgeable',
        'Judiciousness',
        'Sexuality',
        'Selfishness',
        'Industry',
        'Affection',
        'Femininity',
        'Flexibility',
        'Reflectiveness',
        'Decorum',
        'Skepticism',
        'Inhibition',
        'Reticence',
        'Stoicism',
        'Extroversion',
        'Restraint',
        'Physicality',
        'Passivity',
        'Comprehensiveness',
        'Gregariousness',
        'Determination',
        'Visionariness',
        'Joy',
        'Focus',
        'Musicality',
        'Obedience',
        'Endurance',
        'Ribaldry',

        'Reserve',
        'Gentleness',
        'Integrity',
        'Sarcasm',
        'Wanderlust',
        'Timidity',
        'Sociopathy',
        'Intuition',
        'Humor',
        'Sensuality',
        'Tenacity',
        'Loyalty',
        'Curiosity',
        'Decisiveness',
        'Humility',
        'Bulk',
        'Apperception',
        'Candor',
        'Coordination',
        'Vindictiveness',
        'Stubbornness',
        'Innovation',
        'Kindness',
        'Assurance',
        'Facility',
        'Meticulousness',
        'Capriciousness',
        'Fastidiousness',
        'Rhythm',
        'Hubris',
        'Fragility',
        'Leadership',
        'Education',
        'Wisdom',
        'Entitlement',
        'Individualism',
        'Laziness',
        'Forgetfulness',
        'Tenderness',
        'Masculinity',
        'Expressivity',
        'Fashionableness',
        'Fidelity',
        'Spirituality',
        'Patriotism',
        'Brusqueness',
        'Whimsy',
        'Introversion',
        'Strength',
        'Competitiveness',
        'Pride',
        'Consideration',
        'Congeniality',
        'Literalism',
        'Confidence',
        'Courtesy',
        'Morality',
        'Artistry',
        'Faith',
        'Bellicosity',
    ]
    return attributes
        .map((attribute) => {
            return { trait_type: attribute, value: randomValue() }
        })
        .sort((trait1, trait2) => -(trait1.value - trait2.value))
}
