/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Accordion: typeof import('./src/components/nested/Accordion.vue')['default']
    Clicker: typeof import('./src/components/Clicker.vue')['default']
    CNFT: typeof import('./src/components/CNFT.vue')['default']
    FAQ: typeof import('./src/components/FAQ.vue')['default']
    Leaderboard: typeof import('./src/components/Leaderboard.vue')['default']
    Main: typeof import('./src/components/Main.vue')['default']
    MainMenu: typeof import('./src/components/nested/MainMenu.vue')['default']
    NotFound: typeof import('./src/components/NotFound.vue')['default']
    Pagination: typeof import('./src/components/nested/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Satoshi: typeof import('./src/components/Satoshi.vue')['default']
  }
}
